ALTER TABLE public.aufmass_photos
ADD COLUMN IF NOT EXISTS photo_type VARCHAR(50) DEFAULT 'BEFORE',
ADD COLUMN IF NOT EXISTS thumb_url TEXT,
ADD COLUMN IF NOT EXISTS thumb_url_webp TEXT,
ADD COLUMN IF NOT EXISTS storage_bucket TEXT,
ADD COLUMN IF NOT EXISTS storage_path TEXT;
